[package]
name = "guido"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.3"
robotics_lib = { version = "0.1.21", registry = "kellnr" }

